Django6/src/Blog/urls.py
from django.urls import path
from .views import *
app_name='Blog'
urlpatterns=[
    path('',index.as_view(),name='index'),
    path('/<int:post_id>/',detail,name='detail'),
    path('posting/',posting,name='posting'),
    path('search',searchP,name='searchP')
    ]

Django6/src/Django6/urls.py
from django.contrib import admin
from django.urls import path, include
#해당 파일이 view 함수를 알아야되므로 from~import로 함수추가
#urls와 views가 다른 파일 위치이므로 절대경로로 표현

from vote.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('vote/', include('vote.urls')),
    path('login/', include('customlogin.urls') ),
    path('auth/', include('social_django.urls',namespace='social') ),
    path('blog/',include('Blog.urls'))

]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django6/src/customlogin/urls.py
from django.urls.conf import path
from .views import *
from django.contrib.auth import views# 인증(로그인,로그아웃,회원가입)에 관한 뷰가 있는 파일
app_name = 'customlogin'
urlpatterns = [
    path('signup/', signup,name='signup'),
    path('login/', signin,name='signin'),
    path('logout/',views.logout, name='logout')
    ] 

Django6/src/Blog/models.py
from django.db import models
from django.conf import settings
# Create your models here.
# 글 종류 : PostType
class PostType(models.Model):
    name = models.CharField('구분',max_length=50)
    def __str__(self):
        return self.name
# 글 : Post
class Post(models.Model):
    type = models.ForeignKey(PostType,on_delete=models.CASCADE)
    headline = models.CharField('제목',max_length=200)
    #blank : 사용자 입력양식
    #null : 데이터베이스에 저장
    content = models.TextField('내용', blank=True, null=True)
    pub_date = models.DateField('날짜', auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
#이미지,파일을 저장 관리하기 위해서 Django에서 'pillow'라이브러리 사용
#글에 포함된 이미지 : Image
class Image(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    image = models.ImageField('이미지 파일', upload_to='images/%Y/%m/%d')
    def delete(self, using=None, keep_parents=False):
        self.image.delete()
        return models.Model.delete(self, using=using, keep_parents=keep_parents)

#글에 포함된 파일 : File
class File(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    file = models.FileField('파일', upload_to="files/%Y/%m/%d")
    def delete(self, using=None, keep_parents=False):
        self.file.delete()
        return models.Model.delete(self, using=using, keep_parents=keep_parents) 

Django6/src/Blog/forms.py
'''
Created on 2018. 6. 30.

@author: soooo
'''

from django.forms.models import ModelForm
from .models import Post,Image,File

class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ('pub_date','author')
    def __init__(self,*args,**kwargs):
        super(PostForm,self).__init__(*args,**kwargs)
        self.fields['type'].empty_label = None

Django6/src/Blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.list import ListView
from .models import *
from django.contrib.auth.decorators import login_required
from Blog.forms import *
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
#재네릭뷰 : 장고에서 제공하는 여러가지 기능으로 나눈 뷰 클래스
# Create your views here.
#클래스 기반의 뷰
#class 뷰이름(기능별 뷰클래스):
#LlistView : 특정 객체의 목록을 다루는 기능을 가진 뷰 클래스
class index(ListView):
    template_name = "Blog/templates/index.html"
    model = Post
    context_object_name = 'list'
    paginate_by = 5


def detail(request, post_id):
    obj = get_object_or_404(Post,pk=post_id)
    return render(request, 'blog/templates/detail.html',{'post' : obj})


@login_required
def posting(request):
    if request.method == "GET":
        form = PostForm
        return render(request,"blog/templates/posting.html",{"form":form})
    elif request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author = request.user
            obj.save()
            #Image 캑체 생성및 저장
            for f in request.FILES.getlist('images'):
                image = Image(post=obj, image=f)
                image.save()
            for f in request.FILES.getlist('files'):
                file = File(post=obj,file=f)
                file.save()
                
                
            return HttpResponseRedirect( reverse('Blog:detail',args=(obj.id) ) )
        
        
        
def searchP(request):
    q = request.GET.get('q','')
    type = request.GET.get('type','0')
    if type=='0':
        list = Post.objects.filter(headline__contains=q)
        return render(request,"Blog/templates/searchP.html",{'list':list})
    elif type =='1':
        user = User.objects.get(username = q )
        list = Post.objects.filter(author = user)
        return render(request, "Blog/templates/searchP.html",{'list':list})

Django6/src/Blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<a href="{% url 'vote:index' %}">투표 어플리케이션</a>
	<a href="{% url 'Blog:index' %}">블로그 어플리케이션</a>
	{% if user.is_authenticated %}
	<p>{{user.username}}님 <a href="{% url 'customlogin:logout' %}">로그아웃</a></p>
	{% else %}
		<a href="{% url 'customlogin:signup' %}">회원가입</a>
		<a href="{% url 'customlogin:signin' %}">로그인</a>
		{% endif %}
		<hr>
		<form action="{% url 'Blog:searchP' %}"method="GET">
			{% csrf_token %}
			<select name='type'>
				<option value="0" selected>제목</option>
				<option value="1">글쓴이</option>
			</select><input type="text" name='q'/>
			<input type="submit" value="검색"/>
		</form>
		{% block content %}
		{% endblock %}
		<hr>
		<p>서울시 양천구 신월4동</p>
		<p>tel : 010-4023-0457</p>

</body>
</html>

Django6/src/Blog/templates/detail.html
{% extends 'Blog/templates/base.html' %}
{% block content %}
<table>
	<tr>
		<th>제목</th>
		<th>{{ post.headline}}/{{ post.pub_date}}</th>
	</tr>
	<tr>
		<th>글쓴이</th>
		<th>{{post.author.username}}</th>
	</tr>
	<tr>
		<th>내용</th>
		<td>
		{% for f in obj.file_set.all %}
			<a href="{{f.file.url}}"download>다운로드</a>
		{% endfor %}
		{% for i in obj.image_set.all %}
			<img width = 20% src="{{i.image.url}}"/>
		{% endfor %}
		<p>{{ post.content }}</p>
		</td>

	</tr>
</table>



{% endblock %}

Django6/src/Blog/templates/index.html
{% extends 'Blog/templates/base.html' %}
{% block content %}
	{% if page_obj.has_previous %}
		<a href="?page={{ page_obj.previous_page_number}}">◀--</a>
	{% endif %}
	{% if page_obj.has_next %}
		<a href="?page={{ page_obj.next_page_number }}">--▶</a>
	{% endif %}
	<br>
		<table style="width:100%">
			<tr>
				<th>글번호</th>
				<th>제목</th>
				<th>작성자</th>
				<th>날짜</th>
			</tr>
				{% for post in list %}
			
					<tr>
						<th>
							{{post.id}}
						</th>
						<th>
							<a href="{% url 'Blog:detail' post.id %}">{{post.headline}}</a>
						</th>
						<th>
							{{post.author.username}}
						</th>
						<th>
							{{post.pub_date}}
						</th>
					</tr>			
				{% endfor %}
		</table>
	<a href="{% url 'Blog:posting' %}">글쓰기</a>
{% endblock %}

Django6/src/Blog/templates/posting.html
{% extends 'Blog/templates/base.html' %}

{% block content %}
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
		<tr>
			<td>이미지 파일</td>
			<td><input type="file" accept="image/gif, image/jpeg" multiple name="images"></td>
	
	
		</tr>
		<tr>
			<td>첨부 파일</td>
			<td><input type="file" multiple name='files'></td>
		</tr>
	</table>
	<input type="submit" value="글쓰기"/>
</form>
{% endblock %}

Django6/src/Blog/templates/searchP.html
{% extends 'Blog/templates/base.html' %}
{% block content %}
{% if list %}
	<table style="width:100%">
			<tr>
				<th>글번호</th>
				<th>제목</th>
				<th>작성자</th>
				<th>날짜</th>
			</tr>
				{% for post in list %}
			
					<tr>
						<th>
							{{post.id}}
						</th>
						<th>
							<a href="{% url 'Blog:detail' post.id %}">{{post.headline}}</a>
						</th>
						<th>
							{{post.author.username}}
						</th>
						<th>
							{{post.pub_date}}
						</th>
					</tr>			
				{% endfor %}
		</table>
{% else %}
	<p>검색결과가 없습니다.</p>
{% endif %}

{% endblock %}