Django6/src/Blog/urls.py
from django.urls import path
from .views import *
app_name='Blog'
urlpatterns=[
    path('',index.as_view(),name='index'),
    path('/<int:post_id>/',detail,name='detail'),
    path('posting/',posting,name='posting'),
    path('search',searchP,name='searchP')
    ]

Django6/src/Django6/urls.py
from django.contrib import admin
from django.urls import path, include
#해당 파일이 view 함수를 알아야되므로 from~import로 함수추가
#urls와 views가 다른 파일 위치이므로 절대경로로 표현

from vote.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('vote/', include('vote.urls')),
    path('login/', include('customlogin.urls') ),
    path('auth/', include('social_django.urls',namespace='social') ),
    path('blog/',include('Blog.urls'))

]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django6/src/customlogin/urls.py
from django.urls.conf import path
from .views import *
from django.contrib.auth import views# 인증(로그인,로그아웃,회원가입)에 관한 뷰가 있는 파일
app_name = 'customlogin'
urlpatterns = [
    path('signup/', signup,name='signup'),
    path('login/', signin,name='signin'),
    path('logout/',views.logout, name='logout')
    ] 

Django6/src/vote/urls.py
from django.urls import path
from .views import *
#{% url 'vote:index'%}}
app_name = 'vote'
urlpatterns =[
    path('',index,name='index'),
    path('<int:question_id>/', detail,name='detail'),
    path('vote/<int:question_id>/', vote,name='vote'),
    path('result/<int:question_id>/', result,name='result'),
    path('registerQ/', registerQ, name='registerQ'),
    path('deleteQ/<int:question_id>',deleteQ, name='deleteQ'),
    path('registerC/<int:question_id>/', registerC, name='registerC'),
    path('deletC/<int:choice_id>/', deleteC, name='deleteC'),
    path('updateQ/<int:question_id>/',updateQ, name='updateQ'),]

Django6/src/vote/forms.py
'''
Created on 2018. 6. 23.

@author: soooo
'''
from django.forms.models import ModelForm
from . import models
#form : HTML코드에서 사용할 입력방식을 모델클래스에 맞게 자동으로 만들어주는 기능 or 커스텀  입력양식을 만드는 기능을 제공함
#class 폼클래스면(ModelForm): 모델 클래스에 관한 폼을 정의
#class 폼클래스명(Form): HTML에서 사용할 커스텀 폼을 정의

class QuestionForm(ModelForm):
    class Meta: #Meta클레스 ㅓㅇ의를 통해 모델 클래스에 관한 정보 입력
        #model : 모델 클래스명(해당폼이 매칭할 모델클래스 작성)
        #fields or exclude 중 1개 사용
        #fields : 해당 모델폼을 통해 클라이언트가 입력할수 있는 데이터 종류를 작성
        #exclude : 모델클래스의 속성중 명시한 속성을 제외한 속성 사용자 작성
        model = models.Question
        fields = ['question_text']
        #exclude = ['pub_date']  = 속성 제외한 모든 속성을 사용자가 지정
        
        
        
        
        #choice에 대한 모델폼 정의
        #'choice_text', 'question' 속성자만 사용자가 입력하도록 허용
class ChoiceForm(ModelForm):
    class Meta:
        model = models.Choice
        fields = ['choice_text']
        #exclude = ['votes']
        

Django6/src/vote/templates/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- {% : 파이썬 문법 사용 {{ : 해당영역에 데이터 입력 -->
	<!-- Question 객체 안에 있는 question_text값을 입력 -->
	<h1>{{ question.question_text }}</h1>
	<h3>{{ question.author.username }}</h3>
	<form action="{% url 'vote:vote' question.id %}" method="POST">
		{% csrf_token %}
		<!-- 해당 폼이 유효한지 다른 클라이언트에서 접근하지 못하도록 자동발급하는 일회용 키 -->
	<!-- questio.choice_set.all : Question 객체에 엮어있는  모든 Choice객체들을 리스트형태로 반환 -->
		{% for choice in question.choice_set.all %}
			<input type="radio"name="choice"value="{{choice.id}}" 
			id="choice{{forloop.counter}}" />
			<labelfor="choice{{forloop.counter}}">{{ choice.choice_text }}</label>
			{% if user.username == question.author.username %}
				<a href="{% url 'vote:deleteC' choice.id %}">삭제</a>
			{% endif %}
			<br>
		{% endfor %}
	<input type="submit" value="투표"/>
	
	</form>
	<a href="{% url 'vote:index' %}">메인페이지로 돌아가기</a>
	
	<br><br>
	{% if user.username == question.author.username %}
		<a href="{% url 'vote:deleteQ' question.id %}">글 삭제</a>
		<a href="{% url 'vote:updateQ' question.id %}">글 수정</a>
		<a href="{% url 'vote:registerC' question.id%}">답변 등록</a>
	{% endif %}

</body>
</html>

Django6/src/vote/templates/error.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>잘못된 접근</title>
</head>
<body>
	{% if error %}
		<h1>{{ error }}</h1>
	{% endif %}
	
	<a href="{{returnURL}}">해당 글로 넘어가보리기</a>
</body>
</html>

Django6/src/vote/templates/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<!-- 로그인 여부에 따른 링크 보여주기 -->
	<!-- 탬플릿에서 로그인 여부확인서 user변수를 이용함 -->
	<!-- 로그인된 유저의 ID를 추출 : user.username -->
	<!-- 로그인 여부 확인 : user.is_authenticated -> True, False 반환  -->
	{% if user.is_authenticated %}
		<p>{{ user.username }}님 환영합니다.</p>
		<a href="{% url 'customlogin:logout'%}">로그아웃</a>
	{% else %}
		<a href="{% url 'customlogin:signup' %}">회원가입</a>
		<a href="{% url 'customlogin:signin' %}">로그인</a>
		<br>
	{% endif %}
	
	<br>
	<hr>
	
	<!-- HTML파일에서 파이썬 코드를 삽입할 수 있음 for ~ in , if 문 , 외 djengo에서 만든 함수 사용 가능 -->>
	<!-- 단, 함수를 사용할때 소괄호 생략
	ex) 파이선코드 Question.objects.all() ->
	HTML내의 파이썬 코드 -> Question.objects.all -->
	<!-- index 뷰 함수에서 question_list에 넣은 값을 변수처럼 사용 -->
	
	{% for question in question_list %}
	<!-- url 문자열 해당 url에 필요한 값 -->
		<a href="{% url 'vote:detail' question.id %}">{{ question.question_text }}</a>
		<br><!-- 한줄 띄우기 -->
	{% endfor %}
	<!-- if 사용시 endif로 영역 지정
	for 사용시 endfor로 영역 지정 -->
	<br><br>
	<a href="{% url 'vote:registerQ' %}">질문 등록하기</a>
	<br>
</body>
</html>


Django6/src/vote/templates/registerC.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{name}}답변 등록</h1>
	{%if error %}
		<p><b>{{error}}</b></p>
	{% endif %}
	<form action="" method = "POST">
	{% csrf_token %}
	{{ form.as_p}}
	<input type="submit" value="등록">
	</form>

</body>
</html>

Django6/src/vote/templates/registerQ.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>


	<h1>질문 생성</h1>
	<!-- view에서 'error'변수에 값을 넣었는지 확인 -->
	{% if error %}
		<p><strong>{{error}}</strong></p>
	{% endif %}
	
	<form action=""method="POST">
	{% csrf_token %}
	<table>
		{{ form.as_table }}
	</table>
	<!-- 
	<input type="text" name="question_text" maxlength="200" id="a"/>
	<label for="a">질문 이름</label> -->
	<input type="submit" value="만들기"/>
	</form>

</body>
</html>

Django6/src/vote/templates/result.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>{{ obj.question_text }}</h1>
	<h3>{{ obj.pub_date }}</h3>
	<ul>
		{% for item in obj.choice_set.all %}
			<li>{{item.choice_text}}의 투표 수 : {{item.votes}}</li>
		{% endfor %}
	</ul>
	<a href="{% url 'vote:index' %}">메인페이지로 돌아가기</a>
	<a href="{% url 'vote:detail' obj.id %}">다시 투표하기</a>

</body>
</html>

Django6/src/vote/templates/updateQ.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<h1>질문 수정</h1>
	{% if error %}
	<p><b>{{error}}</b></p>
	{% endif %}
	<form action=""method=POST>
		{% csrf_token %}
		<table>
			{{form.as_table}}
		</table>
		<input type="submit"value="수정">
	</form>
</body>
</html>